_target_: animatableGaussian.deformer.smpl_model.SMPLModel
model_path: /root/autodl-tmp/Animatable-3D-Gaussian-master/data/smpl
num_players: ${dataset.num_players}
gender: ${dataset.gender}
num_repeat: 20
max_sh_degree: ${max_sh_degree}
max_freq: ${max_freq}
use_point_color: ${use_point_color}
use_point_displacement: ${use_point_displacement}
enable_ambient_occlusion: ${enable_ambient_occlusion}
non_rigid_name: ${non_rigid_name}
